register with script

diff --git a/minimal_nginx_plus_demo/NGINX-PLUS/scripts/init b/minimal_nginx_plus_demo/NGINX-PLUS/scripts/init
--- a/minimal_nginx_plus_demo/NGINX-PLUS/scripts/init
+++ b/minimal_nginx_plus_demo/NGINX-PLUS/scripts/init
@@ -1,5 +1,20 @@
 #!/bin/sh
 
+prepare_dirs() {
+  LOGDIR=/var/log/wallarm
+  TARANTOOL_LOGFILE=$LOGDIR/tarantool.log
+
+  chown wallarm:wallarm $LOGDIR
+  chmod 0750 $LOGDIR
+
+  touch $TARANTOOL_LOGFILE
+  chown wallarm:wallarm $TARANTOOL_LOGFILE
+
+  touch /etc/crontab /etc/cron.d/*
+
+  mkdir -p /run/supervisor
+}
+
 register_node() {
   args="--batch --no-sync"
 
@@ -51,9 +66,109 @@ register_node() {
   fi
 }
 
-nginx_daemon_off() {
-  nginx -g daemon off
+sync_node() {
+  cmd="/usr/share/wallarm-common/syncnode -l STDOUT"
+
+  for i in $(seq 1 3); do
+    if $cmd; then
+      break
+    elif [ -f /etc/wallarm/proton.db ] && [ -f /etc/wallarm/lom ]; then
+      break
+    else
+      echo "Wait before next syncnode attempt..."
+      sleep 5
+    fi
+  done
 }
 
+configure_nginx() {
+  if [ x"${WALLARM_NGINX_LOG_TO_FILES}" != x"true" ]
+  then
+    ln -sf /dev/stdout /var/log/nginx/access.log
+    ln -sf /dev/stderr /var/log/nginx/error.log
+  fi
+
+  [ -n "$NGINX_BACKEND" ] || return 0
+
+  if [ "$NGINX_BACKEND" = "${NGINX_BACKEND#http://}" ] \
+     && [ "$NGINX_BACKEND" = "${NGINX_BACKEND#https://}" ]
+  then
+    sed -i -e "s#proxy_pass .*#proxy_pass http://$NGINX_BACKEND;#" \
+      /etc/nginx/sites-enabled/default
+  else
+    sed -i -e "s#proxy_pass .*#proxy_pass $NGINX_BACKEND;#" \
+      /etc/nginx/sites-enabled/default
+  fi
+
+  if [ ! -z "$NGINX_PORT" ]; then
+    sed  -i -r "s#(listen.+)80(.+)#\1$NGINX_PORT\2#" \
+      /etc/nginx/sites-enabled/default
+    sed  -i -r "s#(listen.+)80(.+)#\1$NGINX_PORT\2#" \
+      /etc/nginx/conf.d/wallarm-status.conf
+    sed  -i -r "s#http://127.0.0.8/wallarm-status#http://127.0.0.8:$NGINX_PORT/wallarm-status#" \
+      /etc/collectd/wallarm-collectd.conf.d/nginx-wallarm.conf
+  fi
+
+  sed -i -e "s@# wallarm_mode .*@wallarm_mode ${WALLARM_MODE:-monitoring};@" \
+    /etc/nginx/sites-enabled/default
+
+  if [ -n "$WALLARM_APPLICATION" ]; then
+    sed -i -e "s|# wallarm_application .*|wallarm_application $WALLARM_APPLICATION;|" \
+      /etc/nginx/sites-enabled/default
+  fi
+
+  if [ -n "$WALLARM_STATUS_ALLOW" ]; then
+    craft_wallarm_status_snippet
+    insert_wallarm_status_snippet
+  fi
+}
+
+craft_wallarm_status_snippet() {
+  {
+    printf "\tlocation /wallarm-status {\n"
+    for cidr in $(echo "$WALLARM_STATUS_ALLOW" | sed "s/,/ /g"); do
+      printf "\t\tallow %s;\n" "$cidr"
+    done
+    printf "\t\tdeny all;\n"
+    printf "\t\twallarm_status on;\n"
+    printf "\t\twallarm_mode off;\n"
+    printf "\t}\n\n"
+  } >/tmp/wallarm-status.conf
+}
+
+insert_wallarm_status_snippet() {
+  line_for_insert=$(grep -n "location / {" /etc/nginx/sites-enabled/default | cut -f 1 -d:)
+  line_for_insert=$((line_for_insert - 1))
+  sed -i "${line_for_insert}r /tmp/wallarm-status.conf" /etc/nginx/sites-enabled/default
+}
+
+if [ "${1}" = "--source-only" ]
+then
+  return
+fi
+
+if [ x"$WALLARM_FALLBACK" = x"false" ]
+then
+  set -e
+fi
+
+if [ "x${SLAB_ALLOC_ARENA}" = 'x' ]; then
+  if [ -n "$TARANTOOL_MEMORY_GB" ]; then
+    SLAB_ALLOC_ARENA=$TARANTOOL_MEMORY_GB
+    export SLAB_ALLOC_ARENA
+  fi
+fi
+
+
+if [ -z "$DEPLOY_USER" ] || [ -z "$DEPLOY_PASSWORD" ]; then
+  if [ ! -f "/etc/wallarm/license.key" ]; then
+    echo "ERROR: no DEPLOY_USER or DEPLOY_PASSWORD and no license key in /etc/wallarm/license.key" >&2
+    exit 1
+  fi
+fi
+
+prepare_dirs
 register_node
-nginx_daemon_off
+sync_node
+configure_nginx
+nginx
